// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package protocol

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "unicode/utf8"

// Server -> Client: broadcast message from another member
type BroadcastMessage struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Ephemeral sender id (not persisted)
	From string `json:"from"`

	// Payload corresponds to the JSON schema field "payload".
	Payload string `json:"payload"`

	// True if this message is from self (per-recipient)
	Self *bool `json:"self,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type BroadcastMessageType `json:"type"`
}

type BroadcastMessageType string

const BroadcastMessageTypeMessage BroadcastMessageType = "message"

var enumValues_BroadcastMessageType = []interface{}{
	"message",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BroadcastMessageType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BroadcastMessageType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BroadcastMessageType, v)
	}
	*j = BroadcastMessageType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BroadcastMessage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in BroadcastMessage: required")
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in BroadcastMessage: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in BroadcastMessage: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in BroadcastMessage: required")
	}
	type Plain BroadcastMessage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if utf8.RuneCountInString(string(plain.Payload)) > 8192 {
		return fmt.Errorf("field %s length: must be <= %d", "payload", 8192)
	}
	*j = BroadcastMessage(plain)
	return nil
}

// Server -> Client: channel created
type ChannelCreated struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Type corresponds to the JSON schema field "type".
	Type ChannelCreatedType `json:"type"`
}

type ChannelCreatedType string

const ChannelCreatedTypeChannelCreated ChannelCreatedType = "channel_created"

var enumValues_ChannelCreatedType = []interface{}{
	"channel_created",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChannelCreatedType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ChannelCreatedType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ChannelCreatedType, v)
	}
	*j = ChannelCreatedType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChannelCreated) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in ChannelCreated: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in ChannelCreated: required")
	}
	type Plain ChannelCreated
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	*j = ChannelCreated(plain)
	return nil
}

// Client -> Server: request to create a new channel
type CreateChannel struct {
	// Type corresponds to the JSON schema field "type".
	Type CreateChannelType `json:"type"`
}

type CreateChannelType string

const CreateChannelTypeCreateChannel CreateChannelType = "create_channel"

var enumValues_CreateChannelType = []interface{}{
	"create_channel",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CreateChannelType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CreateChannelType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CreateChannelType, v)
	}
	*j = CreateChannelType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CreateChannel) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CreateChannel: required")
	}
	type Plain CreateChannel
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CreateChannel(plain)
	return nil
}

type Error struct {
	// Code corresponds to the JSON schema field "code".
	Code ErrorCode `json:"code"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Type corresponds to the JSON schema field "type".
	Type ErrorType `json:"type"`
}

type ErrorCode string

const ErrorCodeChannelNotFound ErrorCode = "channel_not_found"
const ErrorCodeInternalError ErrorCode = "internal_error"
const ErrorCodeInvalidMessage ErrorCode = "invalid_message"
const ErrorCodeRateLimited ErrorCode = "rate_limited"

var enumValues_ErrorCode = []interface{}{
	"invalid_message",
	"channel_not_found",
	"rate_limited",
	"internal_error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ErrorCode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ErrorCode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ErrorCode, v)
	}
	*j = ErrorCode(v)
	return nil
}

type ErrorType string

const ErrorTypeError ErrorType = "error"

var enumValues_ErrorType = []interface{}{
	"error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ErrorType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ErrorType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ErrorType, v)
	}
	*j = ErrorType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Error) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in Error: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in Error: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Error: required")
	}
	type Plain Error
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Error(plain)
	return nil
}

type JoinChannel struct {
	// Channel identifier
	ChannelId string `json:"channelId"`

	// Type corresponds to the JSON schema field "type".
	Type JoinChannelType `json:"type"`
}

type JoinChannelType string

const JoinChannelTypeJoinChannel JoinChannelType = "join_channel"

var enumValues_JoinChannelType = []interface{}{
	"join_channel",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *JoinChannelType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JoinChannelType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JoinChannelType, v)
	}
	*j = JoinChannelType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *JoinChannel) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in JoinChannel: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in JoinChannel: required")
	}
	type Plain JoinChannel
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	*j = JoinChannel(plain)
	return nil
}

type Joined struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Online corresponds to the JSON schema field "online".
	Online int `json:"online"`

	// Type corresponds to the JSON schema field "type".
	Type JoinedType `json:"type"`
}

type JoinedType string

const JoinedTypeJoined JoinedType = "joined"

var enumValues_JoinedType = []interface{}{
	"joined",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *JoinedType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_JoinedType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_JoinedType, v)
	}
	*j = JoinedType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Joined) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in Joined: required")
	}
	if _, ok := raw["online"]; raw != nil && !ok {
		return fmt.Errorf("field online in Joined: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Joined: required")
	}
	type Plain Joined
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if 1 > plain.Online {
		return fmt.Errorf("field %s: must be >= %v", "online", 1)
	}
	*j = Joined(plain)
	return nil
}

// Client -> Server: E2EE-wrapped new room key (old key encrypts {k: base64url
// 43chars, v:1})
type KeyUpdate struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// E2EE envelope base64url(iv).base64url(messageId).base64url(ct+tag) inner JSON
	// {k:43chars,v:1}
	Payload string `json:"payload"`

	// Type corresponds to the JSON schema field "type".
	Type KeyUpdateType `json:"type"`
}

type KeyUpdateType string

const KeyUpdateTypeKeyUpdate KeyUpdateType = "key_update"

var enumValues_KeyUpdateType = []interface{}{
	"key_update",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KeyUpdateType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_KeyUpdateType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_KeyUpdateType, v)
	}
	*j = KeyUpdateType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KeyUpdate) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in KeyUpdate: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in KeyUpdate: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in KeyUpdate: required")
	}
	type Plain KeyUpdate
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if utf8.RuneCountInString(string(plain.Payload)) > 8192 {
		return fmt.Errorf("field %s length: must be <= %d", "payload", 8192)
	}
	*j = KeyUpdate(plain)
	return nil
}

// Server -> Client: broadcast E2EE-wrapped new key
type KeyUpdated struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Ephemeral sender id
	From string `json:"from"`

	// Payload corresponds to the JSON schema field "payload".
	Payload string `json:"payload"`

	// True if from self
	Self *bool `json:"self,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type KeyUpdatedType `json:"type"`
}

type KeyUpdatedType string

const KeyUpdatedTypeKeyUpdated KeyUpdatedType = "key_updated"

var enumValues_KeyUpdatedType = []interface{}{
	"key_updated",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KeyUpdatedType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_KeyUpdatedType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_KeyUpdatedType, v)
	}
	*j = KeyUpdatedType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *KeyUpdated) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in KeyUpdated: required")
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in KeyUpdated: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in KeyUpdated: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in KeyUpdated: required")
	}
	type Plain KeyUpdated
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if utf8.RuneCountInString(string(plain.Payload)) > 8192 {
		return fmt.Errorf("field %s length: must be <= %d", "payload", 8192)
	}
	*j = KeyUpdated(plain)
	return nil
}

type LeaveChannel struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Type corresponds to the JSON schema field "type".
	Type LeaveChannelType `json:"type"`
}

type LeaveChannelType string

const LeaveChannelTypeLeaveChannel LeaveChannelType = "leave_channel"

var enumValues_LeaveChannelType = []interface{}{
	"leave_channel",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LeaveChannelType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LeaveChannelType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LeaveChannelType, v)
	}
	*j = LeaveChannelType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LeaveChannel) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in LeaveChannel: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in LeaveChannel: required")
	}
	type Plain LeaveChannel
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	*j = LeaveChannel(plain)
	return nil
}

type Left struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Type corresponds to the JSON schema field "type".
	Type LeftType `json:"type"`
}

type LeftType string

const LeftTypeLeft LeftType = "left"

var enumValues_LeftType = []interface{}{
	"left",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LeftType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LeftType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LeftType, v)
	}
	*j = LeftType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Left) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in Left: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Left: required")
	}
	type Plain Left
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	*j = Left(plain)
	return nil
}

// Server -> Client: broadcast E2EE-wrapped nickname
type NicknameUpdated struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Ephemeral sender id
	From string `json:"from"`

	// Payload corresponds to the JSON schema field "payload".
	Payload string `json:"payload"`

	// True if from self
	Self *bool `json:"self,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type NicknameUpdatedType `json:"type"`
}

type NicknameUpdatedType string

const NicknameUpdatedTypeNicknameUpdated NicknameUpdatedType = "nickname_updated"

var enumValues_NicknameUpdatedType = []interface{}{
	"nickname_updated",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NicknameUpdatedType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NicknameUpdatedType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NicknameUpdatedType, v)
	}
	*j = NicknameUpdatedType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NicknameUpdated) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in NicknameUpdated: required")
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in NicknameUpdated: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in NicknameUpdated: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in NicknameUpdated: required")
	}
	type Plain NicknameUpdated
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if utf8.RuneCountInString(string(plain.Payload)) > 8192 {
		return fmt.Errorf("field %s length: must be <= %d", "payload", 8192)
	}
	*j = NicknameUpdated(plain)
	return nil
}

type OnlineCount struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Count corresponds to the JSON schema field "count".
	Count int `json:"count"`

	// Type corresponds to the JSON schema field "type".
	Type OnlineCountType `json:"type"`
}

type OnlineCountType string

const OnlineCountTypeOnlineCount OnlineCountType = "online_count"

var enumValues_OnlineCountType = []interface{}{
	"online_count",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OnlineCountType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OnlineCountType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OnlineCountType, v)
	}
	*j = OnlineCountType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OnlineCount) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in OnlineCount: required")
	}
	if _, ok := raw["count"]; raw != nil && !ok {
		return fmt.Errorf("field count in OnlineCount: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in OnlineCount: required")
	}
	type Plain OnlineCount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if 0 > plain.Count {
		return fmt.Errorf("field %s: must be >= %v", "count", 0)
	}
	*j = OnlineCount(plain)
	return nil
}

// Server -> Client: broadcast E2EE-wrapped room name
type RoomNameUpdated struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Ephemeral sender id
	From string `json:"from"`

	// Payload corresponds to the JSON schema field "payload".
	Payload string `json:"payload"`

	// True if from self
	Self *bool `json:"self,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type RoomNameUpdatedType `json:"type"`
}

type RoomNameUpdatedType string

const RoomNameUpdatedTypeRoomNameUpdated RoomNameUpdatedType = "room_name_updated"

var enumValues_RoomNameUpdatedType = []interface{}{
	"room_name_updated",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RoomNameUpdatedType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RoomNameUpdatedType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RoomNameUpdatedType, v)
	}
	*j = RoomNameUpdatedType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RoomNameUpdated) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in RoomNameUpdated: required")
	}
	if _, ok := raw["from"]; raw != nil && !ok {
		return fmt.Errorf("field from in RoomNameUpdated: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in RoomNameUpdated: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in RoomNameUpdated: required")
	}
	type Plain RoomNameUpdated
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if utf8.RuneCountInString(string(plain.Payload)) > 8192 {
		return fmt.Errorf("field %s length: must be <= %d", "payload", 8192)
	}
	*j = RoomNameUpdated(plain)
	return nil
}

// Single source of truth for client<->server WebSocket messages. TS and Go types
// are generated.
type SchemaJson map[string]interface{}

// Client -> Server: send plaintext (P0) / ciphertext (P2) to channel
type SendMessage struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// Payload corresponds to the JSON schema field "payload".
	Payload string `json:"payload"`

	// Type corresponds to the JSON schema field "type".
	Type SendMessageType `json:"type"`
}

type SendMessageType string

const SendMessageTypeSendMessage SendMessageType = "send_message"

var enumValues_SendMessageType = []interface{}{
	"send_message",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SendMessageType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SendMessageType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SendMessageType, v)
	}
	*j = SendMessageType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SendMessage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in SendMessage: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in SendMessage: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SendMessage: required")
	}
	type Plain SendMessage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if utf8.RuneCountInString(string(plain.Payload)) > 8192 {
		return fmt.Errorf("field %s length: must be <= %d", "payload", 8192)
	}
	*j = SendMessage(plain)
	return nil
}

// Client -> Server: E2EE-wrapped nickname inner JSON {t:"nick",v:1,nick:1-20chars}
type SetNickname struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// E2EE envelope inner {t:"nick",v:1,nick:string}
	Payload string `json:"payload"`

	// Type corresponds to the JSON schema field "type".
	Type SetNicknameType `json:"type"`
}

type SetNicknameType string

const SetNicknameTypeSetNickname SetNicknameType = "set_nickname"

var enumValues_SetNicknameType = []interface{}{
	"set_nickname",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetNicknameType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SetNicknameType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SetNicknameType, v)
	}
	*j = SetNicknameType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetNickname) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in SetNickname: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in SetNickname: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SetNickname: required")
	}
	type Plain SetNickname
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if utf8.RuneCountInString(string(plain.Payload)) > 8192 {
		return fmt.Errorf("field %s length: must be <= %d", "payload", 8192)
	}
	*j = SetNickname(plain)
	return nil
}

// Client -> Server: E2EE-wrapped room display name inner JSON
// {t:"room_name",v:1,name:1-32chars}
type SetRoomName struct {
	// ChannelId corresponds to the JSON schema field "channelId".
	ChannelId string `json:"channelId"`

	// E2EE envelope inner {t:"room_name",v:1,name:string}
	Payload string `json:"payload"`

	// Type corresponds to the JSON schema field "type".
	Type SetRoomNameType `json:"type"`
}

type SetRoomNameType string

const SetRoomNameTypeSetRoomName SetRoomNameType = "set_room_name"

var enumValues_SetRoomNameType = []interface{}{
	"set_room_name",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetRoomNameType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SetRoomNameType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SetRoomNameType, v)
	}
	*j = SetRoomNameType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SetRoomName) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["channelId"]; raw != nil && !ok {
		return fmt.Errorf("field channelId in SetRoomName: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in SetRoomName: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SetRoomName: required")
	}
	type Plain SetRoomName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-zA-Z0-9_-]{1,64}$`, string(plain.ChannelId)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "ChannelId", `^[a-zA-Z0-9_-]{1,64}$`)
	}
	if utf8.RuneCountInString(string(plain.Payload)) > 8192 {
		return fmt.Errorf("field %s length: must be <= %d", "payload", 8192)
	}
	*j = SetRoomName(plain)
	return nil
}
