/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single source of truth for client<->server WebSocket messages. TS and Go types are generated.
 */
export type ChatProtocol =
  | CreateChannel
  | JoinChannel
  | LeaveChannel
  | SendMessage
  | ChannelCreated
  | Joined
  | Left
  | BroadcastMessage
  | OnlineCount
  | Error;

/**
 * Client -> Server: request to create a new channel
 */
export interface CreateChannel {
  type: "create_channel";
}
export interface JoinChannel {
  type: "join_channel";
  /**
   * Channel identifier
   */
  channelId: string;
}
export interface LeaveChannel {
  type: "leave_channel";
  channelId: string;
}
/**
 * Client -> Server: send plaintext (P0) / ciphertext (P2) to channel
 */
export interface SendMessage {
  type: "send_message";
  channelId: string;
  payload: string;
}
/**
 * Server -> Client: channel created
 */
export interface ChannelCreated {
  type: "channel_created";
  channelId: string;
}
export interface Joined {
  type: "joined";
  channelId: string;
  online: number;
}
export interface Left {
  type: "left";
  channelId: string;
}
/**
 * Server -> Client: broadcast message from another member
 */
export interface BroadcastMessage {
  type: "message";
  channelId: string;
  payload: string;
  /**
   * Ephemeral sender id (not persisted)
   */
  from: string;
}
export interface OnlineCount {
  type: "online_count";
  channelId: string;
  count: number;
}
export interface Error {
  type: "error";
  code: "invalid_message" | "channel_not_found" | "rate_limited" | "internal_error";
  message: string;
}
